"""add header_image_url to company

Revision ID: 0c1a5dfac6f4
Revises: 6fe16af27da1
Create Date: 2026-03-09 21:50:11.219765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1a5dfac6f4'
down_revision = '6fe16af27da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('header_image_url')

    # ### end Alembic commands ###
