"""add subscriptions table

Revision ID: 6fe16af27da1
Revises: c4f9e2a1b3d7
Create Date: 2026-02-22 11:37:22.303896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe16af27da1'
down_revision = 'c4f9e2a1b3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mp_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('mp_payer_id', sa.String(length=100), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payable_due_date'))

    with op.batch_alter_table('accounts_receivable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_receivable_due_date'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_invoices_access_key'))
        batch_op.drop_index(batch_op.f('idx_invoices_number'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transactions_company'))
        batch_op.drop_index(batch_op.f('idx_transactions_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_transactions_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_company'), ['company_id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_invoices_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_invoices_access_key'), ['access_key'], unique=False)

    with op.batch_alter_table('accounts_receivable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_receivable_due_date'), ['due_date'], unique=False)

    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payable_due_date'), ['due_date'], unique=False)

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
