"""Add business_configs table

Revision ID: b0b804b79a75
Revises: 76f1b3a8178a
Create Date: 2026-02-08 17:39:44.475920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b804b79a75'
down_revision = '76f1b3a8178a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('module_appointments', sa.Boolean(), nullable=True),
    sa.Column('module_customers', sa.Boolean(), nullable=True),
    sa.Column('module_products', sa.Boolean(), nullable=True),
    sa.Column('module_stock', sa.Boolean(), nullable=True),
    sa.Column('module_services', sa.Boolean(), nullable=True),
    sa.Column('module_gallery', sa.Boolean(), nullable=True),
    sa.Column('appointment_duration_default', sa.Integer(), nullable=True),
    sa.Column('appointment_interval', sa.Integer(), nullable=True),
    sa.Column('appointment_advance_days', sa.Integer(), nullable=True),
    sa.Column('allow_online_booking', sa.Boolean(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=True),
    sa.Column('show_product_prices', sa.Boolean(), nullable=True),
    sa.Column('show_product_stock', sa.Boolean(), nullable=True),
    sa.Column('allow_product_images', sa.Boolean(), nullable=True),
    sa.Column('services_list', sa.JSON(), nullable=True),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('customer_fields', sa.JSON(), nullable=True),
    sa.Column('send_email_confirmation', sa.Boolean(), nullable=True),
    sa.Column('send_sms_reminder', sa.Boolean(), nullable=True),
    sa.Column('reminder_hours_before', sa.Integer(), nullable=True),
    sa.Column('public_welcome_text', sa.Text(), nullable=True),
    sa.Column('public_footer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_configs')
    # ### end Alembic commands ###
